FROM mysql:8.0.32

# 添加容器启动时执行SQL
COPY chatgpt-bootstrap/src/main/resources/db/schema-mysql.sql /docker-entrypoint-initdb.d/init.sql

# 设置terminal进入docker后的默认目录
WORKDIR /usr/bin

# 声明日志数据卷
VOLUME /var/log/mysql
# 声明数据数据卷
VOLUME /var/lib/mysql
# 本地映射配置数据卷
VOLUME /etc/mysql/conf.d

# 暴露端口为3309
EXPOSE 3309

# 设置MySQL root的密码
ENV MYSQL_ROOT_PASSWORD=123456

CMD ["mysqld"]
