version: '3'
services:
  # MySQL 服务
  mysql_gpt:
#    image: hncboy/chatgpt-web-java-mysql:latest
    image: mysql_gpt_img
    container_name: mysql_gpt
    ports:
      - "3309:3306"
    volumes:
      - ~/mydata/mysql/data:/var/lib/mysql #数据文件挂载
      - ~/mydata/mysql/conf:/etc/mysql/conf.d #配置文件挂载
      - ~/mydata/mysql/log:/var/log/mysql #日志文件挂载
    networks:
      gpt_network:
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping" , "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5
  # Redis 服务
  redis_gpt:
    image: redis:7.0.11
    container_name: redis_gpt
    command: redis-server --requirepass 123456
    restart: always
    ports:
      - "6376:6379"
    networks:
      gpt_network:
networks:
  gpt_network:

